# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b7762f70a9aa9a6915e8607eabd22daf4b7a003b310b6cc5b01616f22dbf12ea7105bff4415cc3d35e9f4715bd0ca684c971ab33d2c55a73044545e72a97cde

test:
  secret_key_base: e135a8def6a210cd5e13534d5c2d3b3324d36a21372d27ead6ef88299275fdebfbdab0ef3ab7e0eff049175d0a28227a399b9df9dbee8946981d662acce5c07e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
